Repository JoaquinDeLuca/mytinerary-deluca-ochoa-ojeda, pull requests merged in 2022-09, with the labels that each got.

#71 Issue 18
  src/components/Carousel.js
  src/components/CarouselCities.js
Labels: database

#73 27-redux
  package-lock.json
  package.json
  src/components/Allcity.js
  src/components/PrintCity.js
  src/features/citiesApi.js
  src/features/store.js
  src/index.js
Labels: redux

#76 Issue 31
  src/components/Itinerary.js
  src/styles/Itinerary.css
Labels: Component

#78 Issue-37
  src/App.js
  src/pages/MyTineraries.js
  src/styles/MyTineraries.css
Labels: Component

#79 Issue 35
  src/components/Activities.js
  src/components/Itinerary.js
  src/styles/Activities.css
  src/styles/Itinerary.css
Labels: Component

#80 Issue 27 filter
  src/components/Allcity.js
  src/features/citiesApi.js
Labels: redux

#81 Issue 28 redux
  src/components/Carousel.js
  src/components/CarouselCities.js
Labels: redux

#82 Issue 29
  src/components/Input.js
  src/features/citiesApi.js
Labels: redux

#86 Issue-google
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Carousel.js
  src/components/Header.js
  src/components/SingUpGoogle.js
  src/components/SingUpInput.js
  src/features/store.js
  src/features/userApi.js
  src/pages/Singup.js
  src/styles/SingUpInput.css
Labels: Component

#87 Issue-Singin-32
  src/App.js
  src/components/Header.js
  src/components/SingInForm.js
  src/components/SingUpGoogle.js
  src/features/userApi.js
  src/pages/SingIn.js
  src/styles/SingInForm.css
Labels: Component

#106 Alerts
  src/assets/icons/check.png
  src/assets/icons/exclamation.png
  src/assets/icons/info.png
  src/assets/icons/warning.png
  src/components/alerts/Alert.js
  src/styles/Alert.css
Labels: Component

#109 All alerts
  src/components/Input.js
  src/components/SingInForm.js
  src/components/SingInGoogle.js
  src/components/SingUpGoogle.js
  src/components/SingUpInput.js
  src/components/alerts/Alert.js
  src/features/userApi.js
Labels: Component

#118 Sign in token
  src/App.css
  src/App.js
  src/components/Header.js
  src/components/SingInForm.js
  src/components/SingInGoogle.js
  src/components/SingUpInput.js
  src/features/UserSlice.js
  src/features/store.js
  src/features/userApi.js
  src/styles/Header.css
  src/styles/SingUpInput.css
Labels: redux

#119 Issue-48
  src/App.js
  src/components/Itinerary.js
  src/components/Like.js
  src/features/itinerariesApi.js
  src/styles/Like.css
Labels: Component

#120 Issue 49
  src/components/Comments.js
  src/components/comments/Comment.js
  src/components/comments/CreateComment.js
  src/components/comments/DeleteComment.js
  src/features/commentsApi.js
  src/features/store.js
  src/styles/Comments.css
Labels: database, redux, fix, Component

#121 Issue 45 46
  src/App.js
  src/components/Details.js
  src/components/Header.js
  src/components/NewActivity.js
  src/components/UserMytineraries.js
  src/features/UserSlice.js
  src/features/itinerariesApi.js
  src/pages/MyProfile.js
  src/pages/NewItinerary.js
  src/pages/UserAdmin.js
  src/styles/Activities.css
  src/styles/ActivityAnditinerary.css
  src/styles/Details.css
  src/styles/MyProfile.css
Labels: bug, Component

#125 Issue fixes
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/Activities.js
  src/components/Details.js
  src/components/Footer.js
  src/components/FormEditCity.js
  src/components/Header.js
  src/components/Input.js
  src/components/InputData.js
  src/components/InputNewAdmin.js
  src/components/Like.js
  src/components/NewActivity.js
  src/components/ScrollToTop.js
  src/components/SingInForm.js
  src/components/SingUpInput.js
  src/components/UserMytineraries.js
  src/components/carousel/Arrow.js
  src/components/carousel/Carousel.js
  src/components/carousel/CarouselCities.js
  src/components/carousel/CitiesView.js
  src/components/cities/Cities.js
  src/components/cities/City.js
  src/components/header/Links.js
  src/components/itinerary/Activities.js
  src/components/itinerary/Comments.js
  src/components/itinerary/Itineraries.js
  src/components/itinerary/Like.js
  src/components/itinerary/activities/Activity.js
  src/components/itinerary/comments/Comment.js
  src/components/itinerary/comments/CreateComment.js
  src/components/itinerary/comments/DeleteComment.js
  src/components/itinerary/itineraries/Itinerary.js
  src/features/itinerariesApi.js
  src/features/store.js
  src/pages/Cities.js
  src/pages/EditInerary.js
  src/pages/Home.js
  src/pages/MyProfile.js
  src/pages/MyTineraries.js
  src/pages/NewItinerary.js
  src/pages/SingIn.js
  src/pages/Singup.js
  src/pages/UnderConstruction.js
  src/pages/UserAdmin.js
Labels: bug, redux, fix, Component

#126 Sprint 5
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/components/Activities.js
  src/components/Details.js
  src/components/Footer.js
  src/components/FormEditCity.js
  src/components/Header.js
  src/components/Input.js
  src/components/InputData.js
  src/components/InputNewAdmin.js
  src/components/Like.js
  src/components/NewActivity.js
  src/components/ScrollToTop.js
  src/components/SingInForm.js
  src/components/SingUpInput.js
  src/components/UserMytineraries.js
  src/components/carousel/Arrow.js
  src/components/carousel/Carousel.js
  src/components/carousel/CarouselCities.js
  src/components/carousel/CitiesView.js
  src/components/cities/Cities.js
  src/components/cities/City.js
  src/components/header/Links.js
  src/components/itinerary/Activities.js
  src/components/itinerary/Comments.js
  src/components/itinerary/Itineraries.js
  src/components/itinerary/Like.js
  src/components/itinerary/activities/Activity.js
  src/components/itinerary/comments/Comment.js
  src/components/itinerary/comments/CreateComment.js
  src/components/itinerary/comments/DeleteComment.js
  src/components/itinerary/itineraries/Itinerary.js
  src/features/itinerariesApi.js
  src/features/store.js
  src/pages/Cities.js
  src/pages/EditInerary.js
  src/pages/Home.js
  src/pages/MyProfile.js
  src/pages/MyTineraries.js
  src/pages/NewItinerary.js
  src/pages/SingIn.js
  src/pages/Singup.js
  src/pages/UnderConstruction.js
  src/pages/UserAdmin.js
Labels: bug, redux, fix, Component

#127 Input proyect
  package-lock.json
  package.json
  src/components/itinerary/comments/Comment.js
  src/components/itinerary/comments/CreateComment.js
  src/components/itinerary/comments/TextEditor.js
  src/styles/Comments.css
  src/styles/TextEditor.css
Labels: Component

#128 Sprint 5
  package-lock.json
  package.json
  src/components/itinerary/comments/Comment.js
  src/components/itinerary/comments/CreateComment.js
  src/components/itinerary/comments/TextEditor.js
  src/styles/Comments.css
  src/styles/TextEditor.css
Labels: Component

#129 Fix
  src/api.js
  src/components/FormEditCity.js
  src/components/UserMytineraries.js
  src/styles/Carousel.css
Labels: fix
